Vagrant.configure("2") do |config|
  k8s_version='1.23.0-00'

  config.vm.box = "hashicorp/bionic64"  

  config.vm.provision :shell, path: "bootstrap-common.sh"

  
  config.vm.define "master" do |master|
    ip_addr = "192.168.1.1"

    master.vm.provider :virtualbox do |vb|
      vb.cpus = 2
      vb.memory = 2048
    end


    master.vm.network "private_network", ip: "#{ip_addr}", virtualbox__intnet: true
    master.vm.hostname = "master"

  
    master.vm.provision :shell, path: "bootstrap-master.sh", env: {"IP_ADDR" => "#{ip_addr}", "KUBE_VERSION" => "#{k8s_version}"}
    
  end

  
  config.vm.define "node01" do |node01|
    ip_addr = "192.168.1.2"
    
    node01.vm.provider :virtualbox do |vb|
      vb.cpus = 2
      vb.memory = 2048
    end

    node01.vm.network "private_network", ip: "#{ip_addr}", virtualbox__intnet: true
    node01.vm.hostname = "node01"

    node01.vm.provision :shell, path: "bootstrap-node.sh", env: {"IP_ADDR" => "#{ip_addr}", "KUBE_VERSION" => "#{k8s_version}"}

  end

end
