Vagrant.configure("2") do |config|
  k8s_version='1.23.0-00'

  # config.vm.disk :disk, size: "20GB", primary: true
  config.vm.define "master" do |master|
    ip_addr = "192.168.1.1"

    master.vm.box = "hashicorp/bionic64"

    master.vm.provider :virtualbox do |vb|
      vb.cpus = 2
      vb.memory = 2048
    end

    master.vm.network "private_network", ip: "#{ip_addr}"
    master.vm.hostname = "master"


    master.vm.provision :shell, path: "bootstrap-master.sh", env: {"IP_ADDR" => "#{ip_addr}", "KUBE_VERSION" => "#{k8s_version}"}
    
  end

  config.vm.define "node01" do |node01|
    ip_addr = "192.168.1.2"

    node01.vm.box = "hashicorp/bionic64"

    node01.vm.provider :virtualbox do |vb|
      vb.cpus = 2
      vb.memory = 2048
    end

    node01.vm.network "private_network", ip: "#{ip_addr}"
    node01.vm.hostname = "node01"

    

  end

end
